M48
; DRILL file {KiCad 6.0.11+dfsg-1} date dom 28 dic 2025, 18:54:03
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-12-28T18:54:03+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X4.45Y-2.45
X4.4606Y-6.2
X7.3394Y-2.45
X7.3394Y-6.2
T0
M30
